### ISSUE TITLE
about anet code

### ISSUE THREAD

**Issue by menghuaa** [MCG-NJU/RTD-Action#20]
您好，我去年复现了rtd 在thumos14数据集上的代码，但是我用同样的环境运行anet的代码，却发生了环境方面的错误，nccl278 error。刚才我发现anet代码中util/misc.py文件中，这个函数torch.distributed.init_process_group(
        backend=args.dist_backend,
        init_method=args.dist_url,
        world_size=args.world_size,
        rank=args.rank,
    )，最后一个参数后面有一个逗号（rank=args.rank,），但是thumos14的代码中是没有，我想问下这个多出来的逗号是一个错误吗？

**Comment by menghuaa** [comment]
集群没有cuda9.2，配transformer多卡分配的环境真是太难了/(ㄒoㄒ)/~~

**Comment by menghuaa** [comment]
因为现在卡都被占了，没办法跑实验，好像您回复的会比显卡来的快，所以先来问一下您

**Comment by menghuaa** [comment]
除了这个问题，我还想问下，你们在将activitynet1.3的特征进行线性插值时，有没有考虑它的帧频变成了25fps呢？因为线性插值的代码中会有计算num_frame和feature_frame的地方。num_frame（视频总帧数）你们是直接取标注json文件中的duration_frame值，还是使用视频的持续时间*25得到呢？因为标注文件中的帧频并不都是25fps，而我们使用的原始特征是以25fps的帧频提取特征。我看您anet.py中的代码好像并没有考虑25fps导致视频总帧数变化这个问题，而是直接采用标注json文件中的duration_frame值。

**Comment by JackyTown** [comment]
I can run the code on my machine.

You can re-scale the feature to 100 with https://github.com/JJBOY/BMN-Boundary-Matching-Network/blob/master/data/activitynet_feature_cuhk/data_process.py.

I do not know the feature FPS, since we directly use the feature of https://github.com/PeisenZhao/Bottom-Up-TAL-with-MR/issues/5.

Although we do not know the feature FPS, feature_frames == num_frames // 16 * 16
We perform interpolation based on the num_frames of json.

**Comment by menghuaa** [comment]
> I can run the code on my machine.
> 
> You can re-scale the feature to 100 with https://github.com/JJBOY/BMN-Boundary-Matching-Network/blob/master/data/activitynet_feature_cuhk/data_process.py.
> 
> I do not know the feature FPS, since we directly use the feature of [PeisenZhao/Bottom-Up-TAL-with-MR#5](https://github.com/PeisenZhao/Bottom-Up-TAL-with-MR/issues/5).
> 
> Although we do not know the feature FPS, feature_frames == num_frames // 16 * 16 We perform interpolation based on the num_frames of json.

can you provide the tsn feature of thumos14?

**Comment by JackyTown** [comment]
https://github.com/wzmsltw/BSN-boundary-sensitive-network
https://drive.google.com/file/d/1ISemndlSDS2FtqQOKL0t3Cjj9yk2yznF/view
